### ISSUE TITLE
Step 2 impossible, doesn't create accounts

### ISSUE THREAD

**Issue by RobertusIT** [xyou365/AutoRclone#10]
Hi,

i use rclone but autorclone can be very great without gdrive limits.

I have a problem when i try to install it in win10.

I have installed all things and when i launch 
python3 gen_sa_accounts.py --quick-setup 5
doesn't create nothing in account folder

I'm stuck on there, please can you help me?

**Comment by sean89503** [comment]
Try python gen_sa_accounts.py --quick-setup 5 , not "python3"

**Comment by RobertusIT** [comment]
> Try python gen_sa_accounts.py --quick-setup 5 , not "python3"

thanks, works !

I'm stuck on Step4.

I setup destination teamdrive.
And i didn't know where can i get destination ID team drive
Add service accounts into your destination Team Drive: python3 add_to_team_drive.py -d SharedTeamDriveDstID

And also about source:
Add service accounts into your source Team Drive: python3 add_to_team_drive.py -d SharedTeamDriveSrcID

I have also another question:

Needed also that i repeat from step 1 to step 5 for source team drive, or needed only for one of them? ( so needed configuration only for source team drive, or only for destination team drive )

Thanks for the support
