### ISSUE TITLE
AttributeError: 'InstalledAppFlow' object has no attribute 'run_console'

### ISSUE THREAD

**Issue by yuandx123** [xyou365/AutoRclone#101]
![image](https://user-images.githubusercontent.com/44541952/218307609-cbb2300b-99de-49e7-a41f-22f5b38d6336.png)
my venv
![image](https://user-images.githubusercontent.com/44541952/218307734-be37fb69-37a1-4168-9216-de9741f3a6a2.png)
same on windows10 & python3.11， is normal on replace the commented code line
![image](https://user-images.githubusercontent.com/44541952/218307931-e1854ee6-f4f2-4553-a359-cf1333e0de24.png)

**Comment by youli023023** [comment]
same issue

**Comment by taoqiko** [comment]
same

**Comment by lives4r** [comment]
pip3 install 'google-api-python-client==1.7.2'
pip3 install 'google-auth==1.8.0'
pip3 install 'google-auth-httplib2==0.0.3'
pip3 install 'google-auth-oauthlib==0.4.1'

**Comment by Dysonsun** [comment]
same issue

**Comment by taoqiko** [comment]
> same issue
pip3 install 'google-api-python-client==1.7.2'
pip3 install 'google-auth==1.8.0'
pip3 install 'google-auth-httplib2==0.0.3'
pip3 install 'google-auth-oauthlib==0.4.1'

**Comment by demetranadya** [comment]
yes, I have the same. I just start a simple python script.  I thing I choose wrong type of application. In documentation Another, I don't see another, I choose Web application. When I try it in the web its ok with status 200. But I copy this python code, put client_secret code near my script and .. get a error.

**Comment by demetranadya** [comment]
google-api-core==2.11.0
google-api-python-client==2.79.0
google-auth==2.16.1
google-auth-httplib2==0.1.0
google-auth-oauthlib==1.0.0
googleapis-common-protos==1.58.0

**Comment by demetranadya** [comment]
google-api-core-2.11.0
 google-api-python-client-2.79.0 
google-auth-httplib2-0.1.0 
googleapis-common-protos-1.58.0 
httplib2-0.21.0 
protobuf-4.22.0 
pyparsing-3.0.9 
uritemplate-4.1.1

google-auth-2.16.1 
google-auth-oauthlib-1.0.0 
requests-oauthlib-1.3.1

**Comment by demetranadya** [comment]
I have this message ERROR: launchpadlib 1.10.13 requires testresources, which is not installed.
ERROR: google-api-core 2.11.0 has requirement google-auth<3.0dev,>=2.14.1, but you'll have google-auth 1.28.0 which is incompatible.

**Comment by orangejx** [comment]
> 

thx so much for your reply, your answer completely resolve the issue

**Comment by fritzklyka** [comment]
Thanks for the tips.
I added a requirements.txt
with:
google-api-python-client==1.7.2
google-auth==1.8.0
google-auth-httplib2==0.0.3
google-auth-oauthlib==0.4.1

Then just ran
python -m pip install -r requirements.txt

Then all went well.

**Comment by george-emerald** [comment]
I'd like this issue re-opened as I'm getting the same error yet the solutions here don't work.

**Comment by spamfro** [comment]
Would that error has something to do with the dropped support for `redirect_uri=urn:ietf:wg:oauth:2.0:oob`?

Please note that solution above suggests linking against a fairly old versions of the API. This may be a hint the backend does NOT support those clients any more.

Does it make sense?  If so, what's the PROPER solution?

Thanks!

**Comment by flipbit03** [comment]
The `run_console()` (OOB) flow has been deprecated by Google, that's why it was removed from newer versions of the Google OAuth connector

**Comment by morebrackets** [comment]
This worked:

google-api-python-client==1.7.2
google-auth==2.14.1
google-auth-httplib2==0.0.3
google-auth-oauthlib==0.4.1

**Comment by JJRicks** [comment]
> The `run_console()` (OOB) flow has been deprecated by Google, that's why it was removed from newer versions of the Google OAuth connector

Looks like they need to update the official beginner's documentation
