### ISSUE TITLE
gen_sa_accounts.py tries to create SA on deleted projects

### ISSUE THREAD

**Issue by harryqt** [xyou365/AutoRclone#15]
When using `run python3 gen_sa_accounts.py --quick-setup -1` it tries to create SA on deleted projects too. It should only try to make SA on active projects.

`gen_sa_accounts.py --list-projects` also returns all projects including deleted projects.

**Comment by ghost** [comment]
me to。
how can fix this ？

**Comment by LeeeMooo** [comment]
#59
