### ISSUE TITLE
Mass deleting Service Account keys

### ISSUE THREAD

**Issue by theg00s3** [xyou365/AutoRclone#28]
For some reason my service accounts have 3-4 keys each, which means that when I run `python3 gen_sa_accounts.py --download-keys [project-id]` I get 300-400 keys. Is there a way to delete all the excess keys from the service accounts without deleting the service accounts themselves?

**Comment by CyberPoison** [comment]
Sorry for late reply but there is a python3 script look here

https://github.com/Rhilip/AutoRclone/blob/master/remove.py

**Comment by theg00s3** [comment]
Cool! Thanks for the help
