### ISSUE TITLE
Stuck on reading source/destination | checks: 0 files

### ISSUE THREAD

**Issue by AnshumanFauzdar** [xyou365/AutoRclone#29]
Copied 736gb successfully but got stuck on dst002: reading source/destination | checks: 0 files

Total Size 4tb, team drive to team drive!

 Command used sudo python3 rclone_sa_magic.py -s source -d destination -dp backup -b 1 -e 600

**Comment by RicePudding0xF** [comment]
How did you fix it?

**Comment by AnshumanFauzdar** [comment]
@RicePudding0xF AutoRclone never worked for me, I switched to gclone for fclone.
But due to new google policies these both are also dead!
