### ISSUE TITLE
How this great tool Bypass daily limits?

### ISSUE THREAD

**Issue by Medow** [xyou365/AutoRclone#5]
Thanks for making this great code.
But i would like to know if this tool can bypass the daily 750Gb copy limit?
Also does it bypass the daily 8TB download limits?
Id yes for both, how can we do it?
Thanks.

**Comment by xyou365** [comment]
Why do you open one issues asking about this? We use many service accounts, each with 750GB. So it becomes daily Nx750G.

**Comment by Medow** [comment]
@xyou365 , thanks for reply.
Sorry for adding my question on reddit two.
Regarding my question, my knowledge before is the daily limit is per google drive account not per API or service account. Which i may be wrong (Please correct me).
If my thought is correct , how this tool help me override daily copy limit from google drive account to other accounts. And how does it help me override daily download limit (8 or 10 TB) per day for each account.
Please excuse me because i am not able to understand how this work.
Thanks again for making this code.
