### ISSUE TITLE
Gen_sa_accounts.py

### ISSUE THREAD

**Issue by TheHamkerCat** [xyou365/AutoRclone#62]
`gen_sa_accounts.py` isn't working it's saying **Remember that you can totally create 12 projects (15 already).**

**Comment by zz10001** [comment]
Hi, Sorry to bother you, have you solved it?

**Comment by zz10001** [comment]
> Hi, Sorry to bother you, have you solved it?

I have solved it by `python3 gen_sa_accounts.py --quick-setup -1`

**Comment by TheHamkerCat** [comment]
> > Hi, Sorry to bother you, have you solved it?
> 
> I have solved it by `python3 gen_sa_accounts.py --quick-setup -1`

oh thanks, it's been 5 months, and i moved on.
