### ISSUE TITLE
Using 600 SA account and each only allow to copy 15GB....

### ISSUE THREAD

**Issue by chchia** [xyou365/AutoRclone#67]
Using 600 SA account and each only allow to copy 15GB....

Failed to copy: googleapi: Error 403: The user's Drive storage quota has been exceeded., storageQuotaExceeded

any solution?

**Comment by chchia** [comment]
damn, i rember i enabled OAuth consent but it turn i i didnt, problem solved.

**Comment by mcdull** [comment]
where did you check you allow to copy 15GB?
I got "dst001: 15GB Done @ 170.754853MB/s | checks: 0 files"
However, among the time spent on 170MB/s, it must not be 15GB.  Probably 1.5TB
