### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Medow** [xyou365/AutoRclone#7]
Hello:
I am starting working with your great tool, but when i start adding my service accounts to google group using the following order:

`python3 add_to_google_group.py -g sa@yourdomain.com`
I get the following error:
`Traceback (most recent call last):
  File "add_to_google_group.py", line 43, in <module>
    flow = InstalledAppFlow.from_client_secrets_file(credentials[0], scopes=[
IndexError: list index out of range`

My test running on Ubuntu and the numbers of service account is 700 service accounts.
Also if i would like to add those service accounts by hand, how can i do that ?
Should i have to grab all email and send them invitation to the group?
Thanks.

**Comment by Medow** [comment]
I figure that i am not using the team drive mail.
Sorry.

**Comment by wiiarctus** [comment]
Hey @Medow, I'm having the same problem and can't get it fixed.. :( How did you fix it, and would you mind sharing what you did on how to fix the issue? Thanks in advance!
