### ISSUE TITLE
Add impersonate to sa_magic.py

### ISSUE THREAD

**Issue by xplorer990** [xyou365/AutoRclone#73]
Source google team drive is view only. Its not possible to crate google groups or add service accounts into team drive.

I want sa to impersonate user@email.com. How do i add this to rclone_sa_magic.py.

**Comment by shinji257** [comment]
Apologies as this is an old post but before I open a new issue to see if it was possible I wanted to check to see if you managed to do this?

I'm in the same boat where I have several drives I want to clone with read only access on a specific email and would like to impersonate it for the transfer over.
