### ISSUE TITLE
Error 403: The user's Drive storage quota has been exceeded.

### ISSUE THREAD

**Issue by elpedriyo** [xyou365/AutoRclone#83]
Hello,

Any idea on why I am receiving these errors:

![image](https://user-images.githubusercontent.com/3207791/139132810-9fbb4eb4-2eb4-42ba-950d-3e2b176561f3.png)

Using this command python3 rclone_sa_magic.py -sp /mnt/media/*** -d *****

Kind regards

**Comment by elpedriyo** [comment]
solved

**Comment by bphucc** [comment]
> solved

How did you solve that?

**Comment by dhtpdud** [comment]
@elpedriyo 
Hi i have same issue
can i ask how solve this issue??

i also copy from rocal to GD
but im using personal GoogleDrive(GD)

Could this possibly be a problem?

**Comment by dhtpdud** [comment]
sorry. 

@nguyenphuc241 
solved.
https://github.com/xyou365/AutoRclone#for-local-to-google-drive-needs-some-testing
