### ISSUE TITLE
Copy整个文件夹到另一台机器上后无法运行

### ISSUE THREAD

**Issue by tyhunter** [xyou365/AutoRclone#9]
换了台vps，利用rclone将整个文件夹copy到新vps上，也安装好了依赖环境，但是在执行从共享文件夹拷贝到TD时一直提示：
Failed to copy: failed to make directory: googleapi: Error 404: File not found: 0AD7f-V*****KFUk9PVA., notFound

确定TD ID是正确的，因为在老机器上也是这么执行，不太清楚是我拷贝漏了东西还是说sa账号只能同时被一台机器使用？

使用的命令如下：
python3 rclone_sa_magic.py -s "1N*******cMM-xkc2Y39jYRAHG253uk" -d 0AD7f-V*****KFUk9PVA -dp "/1127" -b 1 -e 600

**Comment by xyou365** [comment]
> Please make sure the Rclone can read your source and destination directory. Check it using rclone size:
rclone --config rclone.conf size --disable ListR src001:
rclone --config rclone.conf size --disable ListR dst001:
